apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
  labels: { app: nestjs-app }
spec:
  replicas: 2
  selector:
    matchLabels: { app: nestjs-app }
  template:
    metadata:
      labels: { app: nestjs-app }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: app
          image: katerinadud/nestjs-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3001
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "300m", memory: "256Mi" }
          readinessProbe:
            httpGet: { path: /redis, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 3000 }
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
spec:
  selector: { app: nestjs-app }
  ports:
    - name: http
      port: 80
      targetPort: 3001 
