apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels: { app: redis }
spec:
  replicas: 1
  selector:
    matchLabels: { app: redis }
  template:
    metadata:
      labels: { app: redis }
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args: ["redis-server","--appendonly","yes","--requirepass","$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
          livenessProbe:
            exec: { command: ["sh","-lc","redis-cli -a $REDIS_PASSWORD ping | grep PONG"] }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec: { command: ["sh","-lc","redis-cli -a $REDIS_PASSWORD ping | grep PONG"] }
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector: { app: redis }
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
