name: CI/CD (Docker Hub → Kubernetes)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  # змінюй тільки якщо треба інший неймспейс
  NAMESPACE: default
  # твій репозиторій в Docker Hub, наприклад katerinadud/nestjs-app
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.30.0"

      - name: Install kustomize
        run: |
          curl -sSL https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/kustomize

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Ensure namespace exists
        run: |
          kubectl get ns ${{ env.NAMESPACE }} >/dev/null 2>&1 || \
          kubectl create ns ${{ env.NAMESPACE }}

      - name: Apply/Update redis-secret from GitHub Secret
        run: |
          kubectl -n ${{ env.NAMESPACE }} create secret generic redis-secret \
            --from-literal=REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      # Підставляємо свіжий тег образу замість ghcr.io/placeholder у твоєму nestjs-deployment.yaml через Kustomize
      - name: Point manifests to freshly built image
        working-directory: k8s
        run: |
          kustomize edit set image katerinadud/nestjs-app:latest=${{ env.DOCKERHUB_REPO }}:${{ github.sha }}

      - name: Deploy manifests
        run: | 
          kustomize build k8s | kubectl apply -n ${{ env.NAMESPACE }} -f -
          kubectl -n ${{ env.NAMESPACE }} rollout status deploy/nestjs-app --timeout=180s
          kubectl -n ${{ env.NAMESPACE }} get pods,svc,ingress
